### ISSUE TITLE
spicy-dns error "no matching case in switch statement" upon receiving Netbios Host Announcement packet

### ISSUE THREAD

**Issue by Politie-SOC** [zeek/spicy-dns#9]
Hi there,

I have numerous of these errors in my Zeek logs: no matching case in switch statement (/usr/local/zeek/var/lib/zkg/clones/package/spicy-dns/analyzer/analyzer.spicy:133:5-149:7)

While looking at the raw packets, it turns out these errors all are caused by Netbios host announcements (broadcast packets) on port 138. See attachment.

Plugin version v0.0.5

Regards,

John

[spicy-errors.pcap.gz](https://github.com/zeek/spicy-dns/files/12561389/spicy-errors.pcap.gz)

**Comment by bbannier** [comment]
Thank you for the ticket.

This parser registers itself to listen e.g., for traffic on port `137/udp`, https://github.com/zeek/spicy-dns/blob/e2e0e455109b00166b2ad40b9b0adae595a3213f/analyzer/analyzer.evt#L5-L8

Since I see this issue neither with zeek-5.2 nor the current Zeek development branch I suspect this is zeek/zeek#3278 where a Spicy analyzer would incorrectly register itself not just for the given port, but a following port as well (`137/udp` triggering registration for `138/udp` here). This should be fixed in zeek-6.0.1 and the next minor release of Zeek.
